// Game events
module.exports = {
    // Click events
    CLICK: 'CLICK',
    LEVEL_UP: 'LEVEL_UP',
    
    // Company events
    COMPANY_CREATED: 'COMPANY_CREATED',
    COMPANY_UPGRADED: 'COMPANY_UPGRADED',
    COMPANY_DELETED: 'COMPANY_DELETED',
    
    // Reward events
    REWARD_CLAIMED: 'REWARD_CLAIMED',
    AD_WATCHED: 'AD_WATCHED',
    DAILY_REWARD_CLAIMED: 'DAILY_REWARD_CLAIMED',
    
    // User events
    USER_REGISTERED: 'USER_REGISTERED',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
    
    // Market events
    ITEM_PURCHASED: 'ITEM_PURCHASED',
    ITEM_SOLD: 'ITEM_SOLD',
    
    // Partnership events
    PARTNERSHIP_REQUESTED: 'PARTNERSHIP_REQUESTED',
    PARTNERSHIP_ACCEPTED: 'PARTNERSHIP_ACCEPTED',
    PARTNERSHIP_REJECTED: 'PARTNERSHIP_REJECTED',
};
